title: 小溪人体传感器
description: 适合HA的高级雷达传感器
theme: just-the-docs

url: https://human_dectet_homeassistant.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
